### ISSUE TITLE
这个是什么问题呢，大佬指导一下

### ISSUE THREAD

**Issue by jacksonvin** [dsmggm/svjdck#3]
Traceback (most recent call last):
  File "/root/autojdck.py", line 548, in <module>
    asyncio.get_event_loop().run_until_complete(main())  #使用异步I/O循环运行main()函数，启动整个自动登录和滑块验证流程。
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/asyncio/base_events.py", line 654, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/root/autojdck.py", line 542, in main
    await logon_main(chromium_path)    #登录操作，写入ck到文件
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/autojdck.py", line 259, in logon_main
    await validate_logon(usernum, passwd, notes, chromium_path)   #登录
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/autojdck.py", line 282, in validate_logon
    browser = await launch({
              ^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/pyppeteer/launcher.py", line 307, in launch
    return await Launcher(options, **kwargs).launch()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/pyppeteer/launcher.py", line 168, in launch
    self.browserWSEndpoint = get_ws_endpoint(self.url)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/pyppeteer/launcher.py", line 227, in get_ws_endpoint
    raise BrowserError('Browser closed unexpectedly:\n')
pyppeteer.errors.BrowserError: Browser closed unexpectedly

**Comment by wzh213** [comment]
请问你解决了嘛
